apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx-conf: |
    worker_processes  1;

    events {
        use                 epoll;
        worker_connections  128;
    }

    error_log         /var/log/nginx/error.log info;

    http {
        server_tokens off;
        include       /etc/nginx/mime.types;
        charset       utf-8;

        access_log    /var/log/nginx/access.log  combined;

        server {
            listen 443 ssl;
            listen [::]:443 ssl;

            ssl off;
            include /etc/nginx/snippets/self-signed.conf;
            include /etc/nginx/snippets/ssl-params.conf;

            root /var/www/html;
            index index.html;
            
            server_name localhost;

            location / {
                try_files $uri $uri/ =404;
            }
        }

        server {
            server_name localhost;

            listen 80;
            listen [::]:80;

            return 301 https://$server_name$request_uri;
        }
    }
